/** Mirror server MENU_LINK_TO_SLUG for SSR catalog routes */
export const MENU_LINK_TO_SLUG: Record<string, string> = {
  "/laptops": "laptops",
  "/laptops/enthusiast-gaming": "laptops",
  "/laptops/thin-light-gaming": "laptops",
  "/laptops/creator-studio": "laptops",
  "/laptops/accessories/laptop-stands": "laptop-accessories",
  "/laptops/accessories/cooling-pads": "laptop-accessories",
  "/laptops/accessories/premium-sleeves": "laptop-accessories",
  "/laptops/accessories/gan-chargers": "laptop-accessories",
  "/pcs": "prebuilt-pcs",
  "/pcs/ultimate-rigs": "prebuilt-pcs",
  "/pcs/mid-tier-esports": "prebuilt-pcs",
  "/pcs/entry-level": "prebuilt-pcs",
  "/components/processors": "processors",
  "/components/graphics-cards": "graphics-cards",
  "/components/motherboards": "motherboards",
  "/components/memory-storage/ram": "ram",
  "/components/memory-storage/nvme-ssds": "storage",
  "/components/memory-storage/hdd": "storage",
  "/components/power-cooling/psu": "power-supplies",
  "/components/power-cooling/aio-liquid-coolers": "cpu-coolers",
  "/components/power-cooling/case-fans": "case-fans",
  "/components/chassis-modding/pc-cases": "pc-cases",
  "/gaming-gear/input-devices/mechanical-keyboards": "mechanical-keyboards",
  "/gaming-gear/input-devices/wireless-mice": "wireless-mice",
  "/gaming-gear/audio/gaming-headsets": "gaming-headsets",
  "/gaming-furniture/seating/ergonomic-chairs": "gaming-furniture",
  "/gaming-furniture/seating/racing-style-chairs": "gaming-furniture",
  "/gaming-furniture/desks/motorized-standing-desks": "gaming-furniture",
  "/gaming-furniture/mounts-arms/monitor-arms": "gaming-furniture",
};
